-- Run this single command in Supabase SQL Editor (https://supabase.com/dashboard)
-- Project -> SQL Editor -> New Query -> Paste & Run

-- 1. Remove the old category restriction so any category can be added
ALTER TABLE tools DROP CONSTRAINT IF EXISTS tools_category_check;

-- 2. Clear old tools
DELETE FROM tools;

-- 3. Insert all 71 curated tools with all categories
INSERT INTO tools (name, description, category, pricing, rating, url) VALUES
  ('Aider', 'AI pair programming directly in your terminal and git repository', 'Coding', 'Free', 4.9, 'https://aider.chat'),
  ('Cursor', 'AI-first code editor built on VS Code for 10x developer productivity', 'Coding', 'Freemium', 4.8, 'https://cursor.com'),
  ('Codeium', 'Free AI code acceleration and autocomplete for individual developers', 'Coding', 'Free', 4.7, 'https://codeium.com'),
  ('Continue', 'Open-source AI coding assistant inside VS Code and JetBrains', 'Coding', 'Free', 4.8, 'https://continue.dev'),
  ('Bolt.new', 'Prompt, build, and deploy full-stack web applications in the browser', 'Building', 'Freemium', 4.9, 'https://bolt.new'),
  ('Lovable', 'Full-stack AI app builder that turns natural language into production code', 'Building', 'Freemium', 4.8, 'https://lovable.dev'),
  ('v0', 'Vercel''s generative UI tool that creates clean React and Tailwind components', 'Building', 'Freemium', 4.9, 'https://v0.dev'),
  ('Relume', 'Generate complete sitemaps and wireframes for websites in seconds', 'Building', 'Freemium', 4.8, 'https://relume.io'),
  ('Framer AI', 'Design and publish responsive, modern websites with AI layout assistance', 'Building', 'Freemium', 4.6, 'https://framer.com'),
  ('Dora', 'Design 3D and animated websites without writing code using AI', 'Building', 'Freemium', 4.5, 'https://dora.run'),
  ('Webflow AI', 'AI-powered web design, content generation, and styling in Webflow', 'Building', 'Freemium', 4.6, 'https://webflow.com'),
  ('Midjourney', 'State-of-the-art AI image generation and photorealistic visual art', 'Design', 'Paid', 4.9, 'https://midjourney.com'),
  ('Leonardo.ai', 'Create production-ready game assets, concept art, and illustrations', 'Design', 'Freemium', 4.7, 'https://leonardo.ai'),
  ('Krea', 'Real-time AI image generation, upscaling, and pattern generation', 'Design', 'Freemium', 4.8, 'https://krea.ai'),
  ('Magnific', 'AI image upscaler and enhancer that hallucinates incredible high detail', 'Design', 'Paid', 4.7, 'https://magnific.ai'),
  ('Recraft', 'AI vector graphic and 3D icon generator for professional designers', 'Design', 'Freemium', 4.8, 'https://recraft.ai'),
  ('Photoroom', 'Automatic AI background removal, product photography, and object erasing', 'Design', 'Freemium', 4.6, 'https://photoroom.com'),
  ('Canva Magic Studio', 'All-in-one AI design tools for social posts, slides, and branding', 'Design', 'Freemium', 4.8, 'https://canva.com'),
  ('Runway', 'Next-gen AI video generation (Gen-3 Alpha) and multimodal VFX tools', 'Video & Audio', 'Freemium', 4.7, 'https://runwayml.com'),
  ('Pika', 'Idea-to-video platform that turns text and images into dynamic 3D scenes', 'Video & Audio', 'Freemium', 4.6, 'https://pika.art'),
  ('Luma Dream Machine', 'High-fidelity AI video model creating realistic motion and camera moves', 'Video & Audio', 'Freemium', 4.8, 'https://lumalabs.ai/dream-machine'),
  ('Kling AI', 'Advanced cinematic video generation model with physical simulation', 'Video & Audio', 'Freemium', 4.8, 'https://klingai.com'),
  ('ElevenLabs', 'Ultra-realistic voice synthesis, voice cloning, and AI dubbing in 30+ languages', 'Video & Audio', 'Freemium', 4.9, 'https://elevenlabs.io'),
  ('Suno', 'Generate full radio-ready songs with vocals and instruments from a prompt', 'Video & Audio', 'Freemium', 4.8, 'https://suno.com'),
  ('Udio', 'Create studio-quality music tracks with lyrics across any music genre', 'Video & Audio', 'Freemium', 4.8, 'https://udio.com'),
  ('HeyGen', 'AI video generator with photorealistic digital avatars and translation', 'Video & Audio', 'Freemium', 4.7, 'https://heygen.com'),
  ('Descript', 'All-in-one video and podcast editor as simple as editing a text doc', 'Video & Audio', 'Freemium', 4.6, 'https://descript.com'),
  ('Opus Clip', 'Turn long YouTube videos into viral short clips for TikTok and Reels', 'Video & Audio', 'Freemium', 4.7, 'https://opus.pro'),
  ('Notion AI', 'AI writing assistant, summarizer, and Q&A engine inside Notion', 'Productivity', 'Freemium', 4.7, 'https://notion.so'),
  ('Taskade', 'AI agents, task management, and collaborative mind mapping', 'Productivity', 'Freemium', 4.6, 'https://taskade.com'),
  ('Otter.ai', 'Real-time meeting notes, audio transcription, and AI summary insights', 'Productivity', 'Freemium', 4.6, 'https://otter.ai'),
  ('Fireflies.ai', 'Automate meeting notes, transcribe voice calls, and search conversations', 'Productivity', 'Freemium', 4.7, 'https://fireflies.ai'),
  ('Fathom', 'Free AI meeting assistant that records, transcribes, and summarizes Zoom calls', 'Productivity', 'Free', 4.8, 'https://fathom.video'),
  ('Superhuman AI', 'AI-powered email client designed to help you hit Inbox Zero in half the time', 'Productivity', 'Paid', 4.7, 'https://superhuman.com'),
  ('Raycast AI', 'Supercharged Mac launcher with ChatGPT and Claude built into your desktop', 'Productivity', 'Freemium', 4.9, 'https://raycast.com'),
  ('Mem.ai', 'Self-organizing workspace that connects your thoughts and notes with AI', 'Productivity', 'Freemium', 4.4, 'https://mem.ai'),
  ('SciSpace', 'AI research assistant to explain complex scientific papers and equations', 'Research', 'Freemium', 4.8, 'https://typeset.io'),
  ('ChatPDF', 'Chat with any PDF document, research paper, or textbook using AI', 'Research', 'Free', 4.6, 'https://chatpdf.com'),
  ('NotebookLM', 'Google''s AI notebook that grounds analysis in your notes and audio discussions', 'Research', 'Free', 4.9, 'https://notebooklm.google.com'),
  ('Arc Search', 'Browse for me AI search engine that reads webpages and creates summaries', 'Research', 'Free', 4.8, 'https://arc.net'),
  ('AutoGPT', 'Open-source autonomous AI agent framework executing complex multi-step tasks', 'Agents', 'Free', 4.5, 'https://autogpt.net'),
  ('CrewAI', 'Framework for orchestrating autonomous AI agent role-playing teams', 'Agents', 'Free', 4.8, 'https://crewai.com'),
  ('Multion', 'Next-gen AI web browser agent that takes actions and navigates for you', 'Agents', 'Freemium', 4.6, 'https://multion.ai'),
  ('AgentGPT', 'Assemble, configure, and deploy autonomous AI agents directly in the browser', 'Agents', 'Freemium', 4.5, 'https://agentgpt.reworkd.ai'),
  ('Devin', 'The world''s first fully autonomous AI software engineer by Cognition', 'Agents', 'Paid', 4.9, 'https://cognition.ai'),
  ('Mutiny', 'No-code AI personalization platform to convert 2x more website visitors', 'Marketing', 'Paid', 4.6, 'https://mutinyhq.com'),
  ('Surfer SEO', 'Data-driven SEO content editor that helps articles rank #1 on Google', 'Marketing', 'Paid', 4.7, 'https://surferseo.com'),
  ('Anyword', 'Performance copywriting AI that predicts engagement scores before publishing', 'Marketing', 'Freemium', 4.5, 'https://anyword.com'),
  ('Taplio', 'All-in-one AI tool to grow and monetize your personal brand on LinkedIn', 'Marketing', 'Paid', 4.6, 'https://taplio.com'),
  ('Jasper', 'Enterprise AI writing platform with custom brand voice and style guides', 'Writing', 'Paid', 4.5, 'https://jasper.ai'),
  ('Copy.ai', 'AI copywriter for blog posts, email campaigns, and marketing collateral', 'Writing', 'Freemium', 4.6, 'https://copy.ai'),
  ('Writesonic', 'AI article writer and SEO content generation platform', 'Writing', 'Freemium', 4.5, 'https://writesonic.com'),
  ('Sudowrite', 'AI fiction and creative writing companion for novel authors and screenwriters', 'Writing', 'Paid', 4.8, 'https://sudowrite.com'),
  ('QuillBot', 'AI paraphraser, grammar checker, and text summarizer for clear writing', 'Writing', 'Freemium', 4.7, 'https://quillbot.com'),
  ('Lex', 'Modern AI-native word processor with smart feedback and autocomplete', 'Writing', 'Freemium', 4.7, 'https://lex.page'),
  ('Julius AI', 'Chat with your data, generate Python charts, and perform statistical analysis', 'Data Analysis', 'Freemium', 4.8, 'https://julius.ai'),
  ('Rose AI', 'Cloud data platform for finding, cleaning, and visualizing financial data', 'Data Analysis', 'Freemium', 4.6, 'https://rose.ai'),
  ('Akkio', 'Generative analytics and predictive machine learning platform for businesses', 'Data Analysis', 'Paid', 4.5, 'https://akkio.com'),
  ('Polymer', 'No-code AI business intelligence tool that turns spreadsheets into dashboards', 'Data Analysis', 'Freemium', 4.5, 'https://polymersearch.com'),
  ('Tome', 'Generative storytelling platform that turns ideas into interactive pitch decks', 'Presentations', 'Freemium', 4.6, 'https://tome.app'),
  ('Gamma', 'Generate polished presentations, docs, and web pages from text prompts', 'Presentations', 'Freemium', 4.8, 'https://gamma.app'),
  ('Beautiful.ai', 'Smart presentation software with AI slide layouts that adapt automatically', 'Presentations', 'Paid', 4.7, 'https://beautiful.ai'),
  ('Pitch', 'Collaborative presentation software with AI-assisted slide creation', 'Presentations', 'Freemium', 4.6, 'https://pitch.com'),
  ('Luma Genie', 'Generate detailed 3D models and textures from text prompts in seconds', '3D & Animation', 'Free', 4.7, 'https://lumalabs.ai/genie'),
  ('Meshy', '3D generative AI tool for converting text and 2D images into 3D assets', '3D & Animation', 'Freemium', 4.6, 'https://meshy.ai'),
  ('Tripo3D', 'Fast AI 3D model generator for game developers and 3D printing', '3D & Animation', 'Freemium', 4.5, 'https://tripo3d.ai'),
  ('Chatbase', 'Custom ChatGPT bot trained on your website data and documents for support', 'Customer Support', 'Freemium', 4.7, 'https://chatbase.co'),
  ('Dante AI', 'Zero-code custom AI chatbots trained on your business knowledge base', 'Customer Support', 'Freemium', 4.6, 'https://dante-ai.com'),
  ('Clay', 'Automate outbound prospecting with 50+ data providers and AI research agents', 'Sales', 'Freemium', 4.9, 'https://clay.com'),
  ('Lavender', 'AI sales email coach that scores emails and helps get more replies', 'Sales', 'Freemium', 4.8, 'https://lavender.ai'),
  ('Reply.io', 'AI sales engagement platform that automates multichannel cold outreach', 'Sales', 'Freemium', 4.5, 'https://reply.io');
